### ISSUE TITLE
need a guideline or example

### ISSUE THREAD

**Issue by vahidhashemi** [rubenlagus/TelegramApi#1]
Hi,

Couldn't find any working example of how to use your lib. any chance to get a quick and dirty example of how to authenticate with telegram and get user profile/send message/ etc .... ?

One suggestion, if you don't want to write example how about some unit tests for telegram functionalities?

**Comment by pazis** [comment]
@vahidhashemi take a look at https://github.com/rubenlagus/Deepthought

however it didn't help me much! I really need a documented example too :(

**Comment by rubenlagus** [comment]
I'll update Deepthought project to this api as soon as I get some time, please be patient

**Comment by rubenlagus** [comment]
It has been done

**Comment by pazis** [comment]
@rubenlagus wow!! thanks a lot! you're so cool. can you just do me 1 more favor, too? talk to me on telegram! I can't PM you, so I asked my friend to give you my ID. I promise not to diturb you. may you please?

**Comment by rubenlagus** [comment]
@pazis Sorry, my Telegram is already messy enough, any bug/issue in this project can be discussed here better.

**Comment by pazis** [comment]
Well, where do we have to enter the code Telegram sends us?

After running DeepThought.java I get this in output:

SEVERE: KERNELCOMM
java.util.concurrent.TimeoutException
	at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:351)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:326)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:439)
	at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:426)
	at org.telegram.bot.kernel.KernelComm.lambda$doRpcCallSync$0(KernelComm.java:172)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Oct 17, 2016 12:09:39 AM org.telegram.bot.services.BotLogger severe
SEVERE: [KERNELHANDLER] Error getting updates state

Actually I get telegram login code in my phone, but I cant enter it in the console like the previous version. And it keeps sending the code.

**Comment by pazis** [comment]
and one more thing... I run it on Windows, so I don't have \dev\urandom file. in the logs I found the FileNotFoundException for this. does it really matter?

**Comment by pazis** [comment]
oh sorry! I just typed the code in console and it worked! Issue closed!
