### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by HellScre4m** [rubenlagus/TelegramApi#15]
`[18_1_2017_12:27:27] {WARNING} KernelPersistence - Loaded state in 2 ms
[18_1_2017_12:27:28] {SEVERE} KERNELCOMM - java.io.FileNotFoundException: \dev\urandom (The system cannot find the path specified)	at java.io.FileInputStream.open0(Native Method)  
	at java.io.FileInputStream.open(FileInputStream.java:195)  
	at java.io.FileInputStream.<init>(FileInputStream.java:138)  
	at org.telegram.bot.kernel.KernelComm.<init>(KernelComm.java:92)  
	at Test.main(Test.java:17)  
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  
	at java.lang.reflect.Method.invoke(Method.java:498)  
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
`

**Comment by pazis** [comment]
I have the same problem but it looks like that it won't make difference!

**Comment by rubenlagus** [comment]
It is just to solve a problem with entropy in some linux systems. There shouldn't be any problem if it is not found.
