### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by p30arena** [rubenlagus/TelegramApi#42]
```
11-07 14:42:35.868 1171-1270/com.example.yabco.teletest W/System.err: java.lang.NoSuchMethodError: No virtual method org_telegram_mtproto_transport_TcpContext_lambda$connect$1()V in class Lorg/telegram/mtproto/transport/TcpContext; or its super classes (declaration of 'org.telegram.mtproto.transport.TcpContext' appears in /data/app/com.example.yabco.teletest-2/base.apk)
11-07 14:42:35.868 1171-1270/com.example.yabco.teletest W/System.err:     at org.telegram.mtproto.transport.-$Lambda$fsl2Vra2XY1GXovvdpD2eZDs164$1.$m$0(Unknown Source)
11-07 14:42:35.869 1171-1264/com.example.yabco.teletest I/MTPROTO: Adding package: #2 help.getConfig#c4f9186b (6485628911651651588, 1)
11-07 14:42:35.869 1171-1270/com.example.yabco.teletest W/System.err:     at org.telegram.mtproto.transport.-$Lambda$fsl2Vra2XY1GXovvdpD2eZDs164$1.run(Unknown Source)
11-07 14:42:35.869 1171-1270/com.example.yabco.teletest W/System.err:     at jawnae.pyronet.PyroSelector.executePendingTasks(PyroSelector.java:89)
11-07 14:42:35.869 1171-1270/com.example.yabco.teletest W/System.err:     at jawnae.pyronet.PyroSelector.select(PyroSelector.java:74)
11-07 14:42:35.869 1171-1270/com.example.yabco.teletest W/System.err:     at jawnae.pyronet.PyroSelector.select(PyroSelector.java:66)
11-07 14:42:35.869 1171-1264/com.example.yabco.teletest I/MTPROTO: Adding package: #3 ping#7abe77ec (6485628911651651592, 3)
11-07 14:42:35.869 1171-1264/com.example.yabco.teletest I/MTPROTO: Sending Package (6485628911651651596, 4)
11-07 14:42:35.869 1171-1270/com.example.yabco.teletest W/System.err:     at jawnae.pyronet.PyroSelector$1.run(PyroSelector.java:162)
11-07 14:42:35.869 1171-1270/com.example.yabco.teletest W/System.err:     at java.lang.Thread.run(Thread.java:761)
11-07 14:42:35.869 1171-1267/com.example.yabco.teletest I/MTPROTO: Adding msg_ack: 0
```

**Comment by p30arena** [comment]
I'm using android
I've put schema.txt and secretsschema.txt in resources directory

I Cleaned and rebuilt the project
errors are gone
